// This file is auto-generated by scripts/generate-constants.ts
// Do not edit manually. Run `npm run generate` to regenerate.

export const PROJECT_TYPE_DESCRIPTION =
  "The project type. Defaults to 'gradle-project'. Supported values: 'maven-project', 'gradle-project', 'gradle-project-kotlin'.";

export const LANGUAGE_DESCRIPTION =
  "The programming language. Defaults to 'java'. Supported values: 'java', 'kotlin', 'groovy'.";

export const BOOT_VERSION_DESCRIPTION =
  "The Spring Boot version.";

export const GROUP_ID_DESCRIPTION =
  "The group id of the generated project. Defaults to 'com.example'.";

export const ARTIFACT_ID_DESCRIPTION =
  "The artifact id of the generated project. Defaults to 'demo'.";

export const VERSION_DESCRIPTION =
  "The project version. Defaults to '0.0.1-SNAPSHOT'.";

export const PROJECT_NAME_DESCRIPTION =
  "The project name.";

export const PROJECT_DESCRIPTION_DESCRIPTION =
  "The project description.";

export const PACKAGE_NAME_DESCRIPTION =
  "The base package name. Defaults to 'com.example.demo'. Must be a valid Java package name.";

export const PACKAGING_DESCRIPTION =
  "The packaging type. Defaults to 'jar'. Supported values: 'jar', 'war'.";

export const JAVA_VERSION_DESCRIPTION =
  "The Java version to use. Defaults to '17'. Supported values: '26', '25', '21', '17'.";

export const BASE_DIR_DESCRIPTION =
  "The base directory name inside the generated archive. Defaults to the artifact id.";

export const DEPENDENCIES_DESCRIPTION =
  "Comma-separated list of dependency IDs to include. See the 'springinitializr://dependencies' resource for available values.";