/**
 * Fetches Spring Initializr metadata and generates src/tool/constants.ts
 * with up-to-date Java versions and dependency lists.
 *
 * Usage: npx tsx scripts/generate-constants.ts
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_FILE = path.resolve(__dirname, "../src/tool/constants.ts");
const METADATA_URL = "https://start.spring.io/metadata/client";

interface MetadataOption {
  id: string;
}

interface DependencyCategory {
  values: { id: string }[];
}

interface Metadata {
  javaVersion?: { default?: string; values?: MetadataOption[] };
  bootVersion?: { default?: string; values?: MetadataOption[] };
  type?: { default?: string; values?: MetadataOption[] };
  language?: { default?: string; values?: MetadataOption[] };
  packaging?: { default?: string; values?: MetadataOption[] };
  dependencies?: { values?: DependencyCategory[] };
}

async function fetchMetadata(): Promise<Metadata> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 15000);

  try {
    const response = await fetch(METADATA_URL, { signal: controller.signal });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    return (await response.json()) as Metadata;
  } finally {
    clearTimeout(timeout);
  }
}

function formatField(label: string, defaultVal: string | undefined, values: MetadataOption[] | undefined): string {
  const supported = values?.map((v) => `'${v.id}'`).join(", ") ?? "";
  const def = defaultVal ? `Defaults to '${defaultVal}'. ` : "";
  return `${label}. ${def}Supported values: ${supported}.`;
}

async function main() {
  console.log("Fetching Spring Initializr metadata...");
  const m = await fetchMetadata();

  const projectTypeDesc = formatField("The project type", m.type?.default, m.type?.values);
  const languageDesc = formatField("The programming language", m.language?.default, m.language?.values);
  const bootVersionDesc = formatField("The Spring Boot version", m.bootVersion?.default, m.bootVersion?.values);
  const packagingDesc = formatField("The packaging type", m.packaging?.default, m.packaging?.values);
  const javaVersionDesc = formatField("The Java version to use", m.javaVersion?.default, m.javaVersion?.values);

  const allDeps: string[] = [];
  for (const cat of m.dependencies?.values ?? []) {
    for (const dep of cat.values) {
      if (dep.id) allDeps.push(dep.id);
    }
  }
  const depsDesc = `Comma-separated list of dependency IDs to include. Supported values: '${allDeps.join("','")}'.`;

  const content = `// This file is auto-generated by scripts/generate-constants.ts
// Do not edit manually. Run \`npm run generate\` to regenerate.

export const PROJECT_TYPE_DESCRIPTION =
  ${JSON.stringify(projectTypeDesc)};

export const LANGUAGE_DESCRIPTION =
  ${JSON.stringify(languageDesc)};

export const BOOT_VERSION_DESCRIPTION =
  ${JSON.stringify(bootVersionDesc)};

export const GROUP_ID_DESCRIPTION =
  "The group id of the generated project. Defaults to 'com.example'.";

export const ARTIFACT_ID_DESCRIPTION =
  "The artifact id of the generated project. Defaults to 'demo'.";

export const VERSION_DESCRIPTION =
  "The project version. Defaults to '0.0.1-SNAPSHOT'.";

export const PROJECT_NAME_DESCRIPTION =
  "The project name.";

export const PROJECT_DESCRIPTION_DESCRIPTION =
  "The project description.";

export const PACKAGE_NAME_DESCRIPTION =
  "The base package name. Defaults to 'com.example.demo'. Must be a valid Java package name.";

export const PACKAGING_DESCRIPTION =
  ${JSON.stringify(packagingDesc)};

export const JAVA_VERSION_DESCRIPTION =
  ${JSON.stringify(javaVersionDesc)};

export const BASE_DIR_DESCRIPTION =
  "The base directory name inside the generated archive. Defaults to the artifact id.";

export const DEPENDENCIES_DESCRIPTION =
  ${JSON.stringify(depsDesc)};
`;

  fs.writeFileSync(OUTPUT_FILE, content, "utf-8");
  console.log(`Generated ${OUTPUT_FILE}`);
}

main().catch((err) => {
  console.error("Error generating constants:", err);
  process.exit(1);
});